---
title: "Model Building and Comparison"
author: "Kevin S.W. --- UNI: ksw2137"
date: "`r format(Sys.time(), '%x')`"
output: github_document
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}

# global default settings for chunks
knitr::opts_chunk$set(echo = TRUE, 
                      fig.dim = c(10, 4), 
                      fig.align = "center",
                      results = "asis"
                      )

# global settings for color palettes
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

# theme global setting for ggplot
theme_set(theme_minimal() + 
            theme(legend.position = "bottom") +
            theme(plot.title = element_text(hjust = 0.5, size = 12),
                  plot.subtitle = element_text(hjust = 0.5, size = 8))
          )

```

# Required Packages

To consolidate the models and the functions, we will use the `caret` package as well as `yardstick` to be able to compare metrics between different models and select which is the best.

```{r}

library(tidyverse)
library(dplyr)
library(rnhanesdata)
# library(caret)
# library(yardstick)

```

# Data Import

## Activity Data

```{r}

# function to pivot and clean activity data from rnhanesdata package
# activ_pivot <- function(df) {
#   df %>% 
#     janitor::clean_names() %>% 
#     pivot_longer(cols = starts_with("MIN"), names_to = "min", names_prefix = "min", values_to = "activ_count") %>% 
#     mutate(min = as.numeric(min)) %>% 
#     mutate(across(c("seqn", "paxcal", "paxstat", "weekday", "sddsrvyr"), factor)) %>% 
#     group_by(seqn)
# }
# 
# activC <- activ_pivot(PAXINTEN_C)
# activD <- activ_pivot(PAXINTEN_D)

# load activity and flag df
data("PAXINTEN_C"); data("PAXINTEN_D")
data("Flags_C"); data("Flags_D")

# input 0 to any datapoints where flags = 0, meaning accelerometer was not worn.
col_vars = paste0("MIN", 1:1440)
PAXINTEN_C[, col_vars] <- PAXINTEN_C[, col_vars]*Flags_C[, col_vars]
PAXINTEN_D[, col_vars] <- PAXINTEN_D[, col_vars]*Flags_D[, col_vars]



```


## Covariate Data

```{r}

covariate_raw <- process_covar(extractAll = T)

# obtaining df from each NHANES wave
covC <- covariate_raw$Covariate_C %>% janitor::clean_names()
covD <- covariate_raw$Covariate_D %>% janitor::clean_names()

# load .csv containing variables of interest
variable_list <- read_csv("./Datasets/variable_list.csv")

# filter each dataset
covC_filtered <- select_if(covC, names(covC) %in% pull(variable_list, var_name))
covD_filtered <- select_if(covD, names(covD) %in% pull(variable_list, var_name))

# remove original to save memory
rm(list = c("covC", "covD"))

# create a list of column names that are different between wave C and D
sq <- seq(max(length(covC_filtered), length(covD_filtered)))
name_diff <- tibble(names(covC_filtered)[sq], names(covD_filtered)[sq]) %>%
  rename(covC_names = 1, covD_names = 2) %>% 
  mutate(
    different = covC_names == covD_names
  ) %>% 
  filter(different == F)


covAll <- dplyr::union(covC, covD)

names(covC)

```

